import type {
  WorkerPoolOptions,
  QueuedTask,
  WorkerInstance,
  WorkerRequest,
  WorkerResponse
} from './types';

/**
 * Main class that manages the Worker Pool.
 * Implements the Producer-Consumer design pattern to manage a FIFO queue
 * of concurrent asynchronous tasks running on native Bun threads.
 */
export class WorkerPool<InputData = any, OutputData = any> {
  private readonly workerPath: string | URL;
  private readonly size: number;
  private readonly workers: WorkerInstance[] = [];
  private readonly queue: QueuedTask<InputData, OutputData>[] = [];
  private readonly pendingTasks = new Map<
    string,
    {
      resolve: (value: OutputData | PromiseLike<OutputData>) => void;
      reject: (reason?: any) => void;
    }
  >();
  private isDestroyed = false;
  private taskCounter = 0;

  /**
   * Initializes the Worker Pool.
   * 
   * @param workerPath Absolute path or URL of the Worker script (e.g., resolved via `import.meta.resolve("./worker.ts")`).
   * @param options Additional configuration for the Pool, such as the number of threads.
   */
  constructor(workerPath: string | URL, options?: WorkerPoolOptions) {
    this.workerPath = workerPath;
    
    // Determines the pool size based on host hardware if not provided
    const concurrency = typeof navigator !== 'undefined' ? navigator.hardwareConcurrency : 4;
    this.size = options?.size ?? concurrency ?? 4;

    if (this.size <= 0) {
      throw new Error('Worker pool size must be a positive integer.');
    }

    this.initializeWorkers();
  }

  /**
   * Creates and pre-allocates the configured number of Workers in the pool.
   */
  private initializeWorkers(): void {
    for (let i = 0; i < this.size; i++) {
      this.workers.push(this.createWorkerInstance(i));
    }
  }

  /**
   * Instantiates an individual Worker and defines its event and error handlers.
   */
  private createWorkerInstance(index: number): WorkerInstance {
    const worker = new Worker(this.workerPath);
    
    const instance: WorkerInstance = {
      worker,
      status: 'idle',
      activeTaskId: null,
    };

    // Listens to normal processing results from the Worker
    worker.onmessage = (event: MessageEvent<WorkerResponse<OutputData>>) => {
      if (this.isDestroyed) return;

      const { id, data, error } = event.data;
      const pending = this.pendingTasks.get(id);

      // Marks the worker as idle as soon as processing finishes
      if (instance.activeTaskId === id) {
        instance.status = 'idle';
        instance.activeTaskId = null;
      }

      if (pending) {
        this.pendingTasks.delete(id);
        if (error) {
          pending.reject(new Error(error.message));
        } else if (data !== undefined) {
          pending.resolve(data);
        } else {
          pending.reject(new Error('Worker returned success but without data.'));
        }
      }

      // Processes the next queued task, if any
      this.processQueue();
    };

    // Listens to unexpected errors thrown internally inside the Worker thread
    worker.onerror = (errorEvent: ErrorEvent) => {
      if (this.isDestroyed) return;

      // Rejects the active task running on this worker, if any
      if (instance.activeTaskId) {
        const pending = this.pendingTasks.get(instance.activeTaskId);
        if (pending) {
          this.pendingTasks.delete(instance.activeTaskId);
          pending.reject(
            new Error(
              errorEvent.message || 'Worker failed unexpectedly with an internal error.'
            )
          );
        }
      }

      // Terminates the problematic old instance for safety and cleans memory
      worker.terminate();

      // Regenerates the Worker in the same slot to restore pool capacity
      this.workers[index] = this.createWorkerInstance(index);

      // Attempts to process the queue with the new Worker
      this.processQueue();
    };

    return instance;
  }

  /**
   * Submits a task to the pool for processing.
   * If there is an idle Worker, the task starts immediately. Otherwise,
   * it transparently enters the FIFO queue and waits for resources to be freed.
   * 
   * @param data Input data of the task to be passed to the Worker.
   * @returns A Promise that resolves with the result generated by the Worker or rejects in case of error.
   */
  public run(data: InputData): Promise<OutputData> {
    if (this.isDestroyed) {
      return Promise.reject(
        new Error('Cannot submit tasks. The WorkerPool has been destroyed.')
      );
    }

    // Creates a secure unique identifier for this task execution
    const id = `task-${++this.taskCounter}-${Math.random().toString(36).substring(2, 9)}`;

    return new Promise<OutputData>((resolve, reject) => {
      // Looks for an idle Worker
      const idleWorker = this.workers.find((w) => w.status === 'idle');

      if (idleWorker) {
        // Binds the active promise and starts processing in the Worker
        this.pendingTasks.set(id, { resolve, reject });
        this.dispatchTask(idleWorker, id, data);
      } else {
        // Enqueues the task (Producer-Consumer pattern)
        this.queue.push({ id, data, resolve, reject });
      }
    });
  }

  /**
   * Sends the message with the task data to the specific Worker.
   */
  private dispatchTask(instance: WorkerInstance, id: string, data: InputData): void {
    instance.status = 'busy';
    instance.activeTaskId = id;

    const request: WorkerRequest<InputData> = { id, data };
    instance.worker.postMessage(request);
  }

  /**
   * Consumes items from the FIFO queue and dispatches them to Workers as they become available.
   */
  private processQueue(): void {
    if (this.isDestroyed || this.queue.length === 0) return;

    const idleWorker = this.workers.find((w) => w.status === 'idle');
    if (!idleWorker) return;

    // Extracts the first item from the FIFO queue
    const nextTask = this.queue.shift();
    if (nextTask) {
      const { id, data, resolve, reject } = nextTask;
      this.pendingTasks.set(id, { resolve, reject });
      this.dispatchTask(idleWorker, id, data);
    }
  }

  /**
   * Gets the current number of workers actively processing.
   */
  public getActiveWorkerCount(): number {
    return this.workers.filter((w) => w.status === 'busy').length;
  }

  /**
   * Gets the number of tasks waiting in the FIFO queue.
   */
  public getQueueLength(): number {
    return this.queue.length;
  }

  /**
   * Gets the total number of Workers allocated in the Pool.
   */
  public getPoolSize(): number {
    return this.workers.length;
  }

  /**
   * Terminates all active Workers and clears the remaining task queue.
   * Cancels all pending Promises by rejecting them.
   */
  public destroy(): void {
    if (this.isDestroyed) return;
    this.isDestroyed = true;

    // Cancels all tasks that were in the queue without running
    for (const task of this.queue) {
      task.reject(
        new Error('WorkerPool was destroyed before this task could be executed.')
      );
    }
    this.queue.length = 0;

    // Rejects all tasks that were actively running on the threads
    for (const [id, pending] of this.pendingTasks.entries()) {
      pending.reject(
        new Error('WorkerPool was destroyed while processing this task.')
      );
    }
    this.pendingTasks.clear();

    // Physically terminates all workers
    for (const instance of this.workers) {
      instance.worker.terminate();
    }
    this.workers.length = 0;
  }
}
